"""
Detection Analytics

Analyzes YOLO detection CSV files generated by a solar-panel
inspection mission.
"""

import csv
from collections import Counter
from pathlib import Path
from statistics import mean


class DetectionAnalyzer:
    """Analyze detection results from a mission."""

    def __init__(self, detection_file):
        self.detection_file = Path(detection_file)

        if not self.detection_file.exists():
            raise FileNotFoundError(f"Detection file not found: {self.detection_file}")

        self.detections = self._load()

    def _load(self):
        """Load detection records from CSV."""

        with self.detection_file.open(
            "r",
            newline="",
            encoding="utf-8",
        ) as file:

            reader = csv.DictReader(file)

            return list(reader)

    @property
    def total_detections(self):
        """Return total number of detected objects."""

        return len(self.detections)

    @property
    def images_inspected(self):
        """Return number of unique inspected images."""

        images = {detection["Image"] for detection in self.detections}

        return len(images)

    def class_counts(self):
        """Return detection count for each class."""

        return Counter(detection["Class"] for detection in self.detections)

    def average_confidence(self):
        """Return average model confidence."""

        if not self.detections:
            return 0.0

        values = [float(detection["Confidence"]) for detection in self.detections]

        return mean(values)

    def critical_detections(self):
        """Return number of critical detections."""

        return sum(
            1
            for detection in self.detections
            if detection["Class"].lower()
            in {
                "cracked",
                "bird_drop",
            }
        )

    def inspection_status(self):
        """
        Determine overall inspection status.

        CRITICAL:
            Cracked or bird-drop detections found.

        ATTENTION REQUIRED:
            Dust detected but no critical detections.

        NORMAL:
            Only panel detections found.
        """

        counts = self.class_counts()

        if counts["cracked"] > 0 or counts["bird_drop"] > 0:
            return "CRITICAL"

        if counts["dusty"] > 0:
            return "ATTENTION REQUIRED"

        return "NORMAL"

    def summary(self):
        """Return complete analytics summary."""

        counts = self.class_counts()

        return {
            "images_inspected": self.images_inspected,
            "total_detections": self.total_detections,
            "class_counts": dict(counts),
            "average_confidence": self.average_confidence(),
            "critical_detections": self.critical_detections(),
            "inspection_status": self.inspection_status(),
        }
